version: '3'

services:


  #  rabbitmq:
  #    image: "rabbitmq:management"
  #    environment:
  #      RABBITMQ_DEFAULT_USER: guest
  #      RABBITMQ_DEFAULT_PASS: guest
  #    ports:
  #      - "5672:5672"
  #      - "15672:15672"

  hotel:
    build:

      context: .
      dockerfile: ./hotel-catalog-service/Dockerfile
    ports:
      - "80:80"


  booking:
    build:
      context: .
      dockerfile: ./booking-service/Dockerfile
    ports:
      - "81:81"


#  keycloak:
#    image: quay.io/keycloak/keycloak:23.0.1
#    ports:
#      - "8080:8080"
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    command: "start-dev"



volumes:
  postgres_data:
