version: '3'

services:


  hotel:
    build:

      context: .
      dockerfile: ./hotel-catalog-service/Dockerfile
    ports:
      - "82:82"


  booking:
    build:
      context: .
      dockerfile: ./booking-service/Dockerfile
    ports:
      - "81:81"




volumes:
  postgres_data:
